using System.IO;
using System.Security.AccessControl;
using System;

namespace NumberGuessingGame
{
    class Program
    {
        // function to accept number guess from user, it verifies if the input is an integer
        public static int userGuess(){

            int guess;
            input:
            try{
                Console.Write("GUESS: ");
                guess = int.Parse(Console.ReadLine());
                return guess;
            }
            catch (FormatException e){
                Console.WriteLine("Invalid Input:", e);
                goto input;
            }

        }

// function to check the user guess with the randomly generated integer. it takes two parameters, the number of available 
// guesses and the random number generated by the program
        public static void guessChecker(int x, int y){

            int guess;
            int guessCount = 0;

            while(guessCount < x){

                guess = userGuess();
                guessCount++ ;

                if (guess == y){

                    Console.WriteLine("You got it right!");
                    break;

                } else {

                    Console.WriteLine("That was wrong!");
                    int guessesLeft = x - guessCount;
                    Console.WriteLine("You have {0} guesses left!", guessesLeft);
                }
            } 
            Console.WriteLine("Game Over!!!");
        }

// this calls the level functions, according to the level chosen by the user
        public static void play(string level){

                if (level == "easy"){
                Console.WriteLine("Guess a number between 1-10");                
                easy();
            }

            else if ( level == "medium"){
                Console.WriteLine("Guess a number between 1-20");
                medium();
            }

            else if(level == "hard"){
                Console.WriteLine("Guess a number between 1-50");
                hard();
            }

            else {

                Console.WriteLine("Please Enter the correct level!!!");
            }
            
        }

// the easy level function
        public static void easy(){

            int availableGuesses = 6;
            Random random = new Random();
            int secretNum = random.Next(1,10);

            guessChecker(availableGuesses, secretNum);

        }

// medium level
         public static void medium(){
             int availableGuesses = 4;
            Random random = new Random();
            int secretNum = random.Next(1,20);

            guessChecker(availableGuesses, secretNum);
            }

        

// hard level
         public static void hard(){
             int availableGuesses = 3;
            Random random = new Random();
            int secretNum = random.Next(1,50);

            guessChecker(availableGuesses, secretNum);

        }

//main program
        static void Main(string[] args)
        {
            begin:
            string selectLevel;
            Console.WriteLine("Choose Game Level. \n Easy \t Medium \t Hard ");
            selectLevel = (Console.ReadLine()).ToLower();
            play(selectLevel);
//giving the user the power to try again even if he lost
            Console.Write("Do you want to try again? (y/n): ");
            string tryAgain = Console.ReadLine();

            if (tryAgain == "y"){
                goto begin;
            }

            else {
                System.Environment.Exit(0);
            }

        }
    }
}
